<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'UcenterClient\Module'                          => __DIR__ . '/Module.php',
    'UcenterClient\Services\UcenterInterface'       => __DIR__ . '/src/UcenterClient/services/UcenterInterface.php',
    'UcenterClient\Services\Ucenter'                => __DIR__ . '/src/UcenterClient/services/Ucenter.php',
    'UcenterClient\Services\Plugin\SerializerXml'   => __DIR__ . '/src/UcenterClient/services/Plugin/SerializerXml.php',
    'UcenterClient\Services\Plugin\XML'             => __DIR__ . '/src/UcenterClient/services/Plugin/XML.php',
    'UcenterClient\Controller\Plugin\UcNote'        => __DIR__ . '/src/UcenterClient/Controller/Plugin/UcNote.php',
    'UcenterClient\Controller\IndexController'      => __DIR__ . '/src/UcenterClient/Controller/IndexController.php',
    'UcenterClient\Options\ModuleOptions'           => __DIR__ . '/src/UcenterClient/Options/ModuleOptions.php',
    'UcenterClient\Options\UcenterOptionsInterface' => __DIR__ . '/src/UcenterClient/Options/UcenterOptionsInterface.php',
);